/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutJasonRouteImport } from './routes/about-jason'
import { Route as AreasWeCoverRouteImport } from './routes/areas-we-cover'
import { Route as ClientCentredLearningRouteImport } from './routes/client-centred-learning'
import { Route as DrivingLessonsRouteImport } from './routes/driving-lessons'
import { Route as DrivingVideosRouteImport } from './routes/driving-videos'
import { Route as LessonPricesRouteImport } from './routes/lesson-prices'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SemiIntensiveCoursesRouteImport } from './routes/semi-intensive-courses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutJasonRoute = AboutJasonRouteImport.update({
  id: '/about-jason',
  path: '/about-jason',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasWeCoverRoute = AreasWeCoverRouteImport.update({
  id: '/areas-we-cover',
  path: '/areas-we-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCentredLearningRoute = ClientCentredLearningRouteImport.update({
  id: '/client-centred-learning',
  path: '/client-centred-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivingLessonsRoute = DrivingLessonsRouteImport.update({
  id: '/driving-lessons',
  path: '/driving-lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivingVideosRoute = DrivingVideosRouteImport.update({
  id: '/driving-videos',
  path: '/driving-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonPricesRoute = LessonPricesRouteImport.update({
  id: '/lesson-prices',
  path: '/lesson-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SemiIntensiveCoursesRoute = SemiIntensiveCoursesRouteImport.update({
  id: '/semi-intensive-courses',
  path: '/semi-intensive-courses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-jason': typeof AboutJasonRoute
  '/areas-we-cover': typeof AreasWeCoverRoute
  '/client-centred-learning': typeof ClientCentredLearningRoute
  '/driving-lessons': typeof DrivingLessonsRoute
  '/driving-videos': typeof DrivingVideosRoute
  '/lesson-prices': typeof LessonPricesRoute
  '/reviews': typeof ReviewsRoute
  '/semi-intensive-courses': typeof SemiIntensiveCoursesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-jason': typeof AboutJasonRoute
  '/areas-we-cover': typeof AreasWeCoverRoute
  '/client-centred-learning': typeof ClientCentredLearningRoute
  '/driving-lessons': typeof DrivingLessonsRoute
  '/driving-videos': typeof DrivingVideosRoute
  '/lesson-prices': typeof LessonPricesRoute
  '/reviews': typeof ReviewsRoute
  '/semi-intensive-courses': typeof SemiIntensiveCoursesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-jason': typeof AboutJasonRoute
  '/areas-we-cover': typeof AreasWeCoverRoute
  '/client-centred-learning': typeof ClientCentredLearningRoute
  '/driving-lessons': typeof DrivingLessonsRoute
  '/driving-videos': typeof DrivingVideosRoute
  '/lesson-prices': typeof LessonPricesRoute
  '/reviews': typeof ReviewsRoute
  '/semi-intensive-courses': typeof SemiIntensiveCoursesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-jason'
    | '/areas-we-cover'
    | '/client-centred-learning'
    | '/driving-lessons'
    | '/driving-videos'
    | '/lesson-prices'
    | '/reviews'
    | '/semi-intensive-courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-jason'
    | '/areas-we-cover'
    | '/client-centred-learning'
    | '/driving-lessons'
    | '/driving-videos'
    | '/lesson-prices'
    | '/reviews'
    | '/semi-intensive-courses'
  id:
    | '__root__'
    | '/'
    | '/about-jason'
    | '/areas-we-cover'
    | '/client-centred-learning'
    | '/driving-lessons'
    | '/driving-videos'
    | '/lesson-prices'
    | '/reviews'
    | '/semi-intensive-courses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutJasonRoute: typeof AboutJasonRoute
  AreasWeCoverRoute: typeof AreasWeCoverRoute
  ClientCentredLearningRoute: typeof ClientCentredLearningRoute
  DrivingLessonsRoute: typeof DrivingLessonsRoute
  DrivingVideosRoute: typeof DrivingVideosRoute
  LessonPricesRoute: typeof LessonPricesRoute
  ReviewsRoute: typeof ReviewsRoute
  SemiIntensiveCoursesRoute: typeof SemiIntensiveCoursesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-jason': {
      id: '/about-jason'
      path: '/about-jason'
      fullPath: '/about-jason'
      preLoaderRoute: typeof AboutJasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-we-cover': {
      id: '/areas-we-cover'
      path: '/areas-we-cover'
      fullPath: '/areas-we-cover'
      preLoaderRoute: typeof AreasWeCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-centred-learning': {
      id: '/client-centred-learning'
      path: '/client-centred-learning'
      fullPath: '/client-centred-learning'
      preLoaderRoute: typeof ClientCentredLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driving-lessons': {
      id: '/driving-lessons'
      path: '/driving-lessons'
      fullPath: '/driving-lessons'
      preLoaderRoute: typeof DrivingLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driving-videos': {
      id: '/driving-videos'
      path: '/driving-videos'
      fullPath: '/driving-videos'
      preLoaderRoute: typeof DrivingVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-prices': {
      id: '/lesson-prices'
      path: '/lesson-prices'
      fullPath: '/lesson-prices'
      preLoaderRoute: typeof LessonPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semi-intensive-courses': {
      id: '/semi-intensive-courses'
      path: '/semi-intensive-courses'
      fullPath: '/semi-intensive-courses'
      preLoaderRoute: typeof SemiIntensiveCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutJasonRoute: AboutJasonRoute,
  AreasWeCoverRoute: AreasWeCoverRoute,
  ClientCentredLearningRoute: ClientCentredLearningRoute,
  DrivingLessonsRoute: DrivingLessonsRoute,
  DrivingVideosRoute: DrivingVideosRoute,
  LessonPricesRoute: LessonPricesRoute,
  ReviewsRoute: ReviewsRoute,
  SemiIntensiveCoursesRoute: SemiIntensiveCoursesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
